name: Bug Report
description: Report a bug in Tandarr
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Tandarr Version
      description: Docker image tag (e.g., 1.2.3)
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Unraid
        - Docker Compose
        - Docker Run
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste any relevant container logs (`docker logs tandarr`).
      render: shell
